### ISSUE TITLE
malformed pattern (missing ']

### ISSUE THREAD

**Issue by NimaGame** [amirhmz/Xamarin#1]
Hello.
I got this error:
*** 1455884044.512049 lua: .///bot/utils.lua:489: malformed pattern (missing ']
Can you help me please?

**Comment by amirhmz** [comment]
Hello
Thanks to comment this problem
Please get again Clone and fork
The problem now was repaired :)

**Comment by NimaGame** [comment]
Are you sure?
`
 *** 1455974613.025859 lua: .///bot/utils.lua:489: malformed pattern (missing ']')
 [08:23]  🎄NıмαGαмε🎄 >>> !creategroup TEST
 *** 1455974619.418231 lua: .///bot/utils.lua:489: malformed pattern (missing ']')
 [08:23]  🎄NıмαGαмε🎄 >>> !id
`
